## BEGIN IMPORT MODULES
## BEGIN IMPORT MODULES
## BEGIN IMPORT MODULES

import unittest
import pytest
import os
import test_unittests

## END IMPORT MODULES
## END IMPORT MODULES
## END IMPORT MODULES

## BEGIN DECLARE VARIABLES
## BEGIN DECLARE VARIABLES
## BEGIN DECLARE VARIABLES

## END DECLARE VARIABLES
## END DECLARE VARIABLES
## END DECLARE VARIABLES

## BEGIN DEFINE FUNCTIONS
## BEGIN DEFINE FUNCTIONS
## BEGIN DEFINE FUNCTIONS

def fn_DoesObjectExist(NameOfFile):

    ## CALL FUNCTION - CHECKS IF OBJECT EXISTS IN LOCAL FILE PATH 
    DoesObjectExist = os.path.exists(NameOfFile)

    ## TEST - PRINT OUTPUT TO CONSOLE - THIS WILL GIVE US VISUAL CONFIRMATION THAT THIS FUNCTION WAS CALLED
    print("DoesObjectExist = ", DoesObjectExist)

    ## RETURN VARIABLE --> BOOLEAN TRUE or FALSE
    return(DoesObjectExist)


def fn_IsObjectFile(NameOfFile):

    ## CALL FUNCTION - CHECKS IF OBJECT IS OF TYPE FILE
    IsObjectFile = os.path.isfile(NameOfFile)

    ## TEST - PRINT OUTPUT TO CONSOLE - THIS WILL GIVE US VISUAL CONFIRMATION THAT THIS FUNCTION WAS CALLED
    print("IsObjectFile = ", IsObjectFile)

    ## RETURN VARIABLE --> BOOLEAN TRUE or FALSE
    return(IsObjectFile)

## END DEFINE FUNCTIONS
## END DEFINE FUNCTIONS
## END DEFINE FUNCTIONS

## BEGIN MAIN PROGRAM
## BEGIN MAIN PROGRAM
## BEGIN MAIN PROGRAM

if __name__ == "__main__":

    ## EXECUTE UNIT TESTS
    unittest.main(module=test_unittests)
    
    
## END MAIN PROGRAM
## END MAIN PROGRAM
## END MAIN PROGRAM

## GAME OVER
## GAME OVER
## GAME OVER
